env:
  browser: true
  node: true
  es2022: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:react/jsx-runtime
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
settings:
  react:
    version: detect
rules:
  no-unused-vars:
    - error
    - args: none
  react/prop-types:
    - 'off'
